imdb:
  num_layers: 1
  hid_dim: 1792
  proj_dim: 512
  lr: 3.0e-04
  weight_decay: 5.0e-05
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.62
  tau_g: 0.55
  w_g: 4
  w_m: 1
  epochs: 300
  batch_size_1: null
  batch_size_2: null
  wg: 10
  threshold: 0
  c_hypergraph: 2

house:
  num_layers: 1
  hid_dim: 512
  proj_dim: 640
  lr: 1.0e-03
  weight_decay: 1.0e-05
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.02
  tau_g: 0.5
  w_g: 4
  w_m: 1
  epochs: 300
  batch_size_1: null
  batch_size_2: null
  wg: 10
  threshold: 0
  c_hypergraph: 4

aminer:
  num_layers: 1
  hid_dim: 256
  proj_dim: 128
  lr: 1.0e-02
  weight_decay: 1.0e-05
  drop_feature_rate: 0.2
  drop_incidence_rate: 0.2
  tau_n: 1.45
  tau_g: 1.2
  tau_m: 1.0
  w_g: 0.0625
  w_m: 0.25
  epochs: 100
  batch_size_1: 4096
  batch_size_2: 1024
  wg: 0.1
  threshold: 0.3
  c_hypergraph: 1.3

dblp_copub:
  num_layers: 1
  hid_dim: 1280
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 1.0e-04
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.43
  tau_g: 1.45
  w_g: 4
  w_m: 1
  epochs: 300
  batch_size_1: null
  batch_size_2: null
  wg: 5
  threshold: 0.2
  c_hypergraph: 4.9

cora:
  num_layers: 1
  hid_dim: 2048
  proj_dim: 512
  lr: 1.0e-04
  weight_decay: 1.0e-05
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.79
  tau_g: 0.5
  tau_m: 1.0
  w_g: 4
  w_m: 1
  epochs: 300
  batch_size_1: null
  batch_size_2: null
  wg: 3.5
  threshold: 0.3
  c_hypergraph: 8.5


citeseer:
  num_layers: 1
  hid_dim: 768
  proj_dim: 640
  lr: 3.0e-05
  weight_decay: 2.5e-03
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 1.5
  tau_g: 0.75
  tau_m: 0.8
  w_g: 4
  w_m: 2
  epochs: 500
  batch_size_1: null
  batch_size_2: null
  wg: 2.9
  threshold: 0.6
  c_hypergraph: 1

pubmed:
  num_layers: 1
  hid_dim: 1792
  proj_dim: 768
  lr: 1.0e-03
  weight_decay: 5.0e-06
  drop_feature_rate: 0.1
  drop_incidence_rate: 0.4
  tau_n: 0.35
  tau_g: 0.25
  tau_m: 0.6
  w_g: 4
  w_m: 2
  epochs: 300
  batch_size_1: null
  batch_size_2: null
  wg: 20
  threshold: 0
  c_hypergraph: 1

dblp_coauthor:
  num_layers: 1
  hid_dim: 256
  proj_dim: 128
  lr: 1.0e-02
  weight_decay: 1.0e-05
  drop_feature_rate: 0.2
  drop_incidence_rate: 0.2
  tau_n: 0.5
  tau_g: 0.45
  tau_m: 1.0
  w_g: 0.0625
  w_m: 0.25
  epochs: 500
  batch_size_1: 4096
  batch_size_2: 1024
  wg: 0.5
  threshold: 0
  c_hypergraph: 1

zoo:
  num_layers: 1
  hid_dim: 512
  proj_dim: 1024
  lr: 2.0e-03
  weight_decay: 2.0e-08
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.2
  tau_n: 0.28
  tau_g: 0.1
  tau_m: 1.0
  w_g: 2.0
  w_m: 2.0
  epochs: 100
  batch_size_1: null
  batch_size_2: null
  wg: 0.1
  threshold: 0.13
  c_hypergraph: 0.15

NTU2012:
  num_layers: 1
  hid_dim: 640
  proj_dim: 512
  lr: 5.0e-03
  weight_decay: 9.5e-07
  drop_feature_rate: 0.0
  drop_incidence_rate: 0.4
  tau_n: 1.5
  tau_g: 0.58
  tau_m: 0.5
  w_g: 0.5
  w_m: 0.0625
  epochs: 400
  batch_size_1: null
  batch_size_2: null
  wg: 10
  threshold: 0.4
  c_hypergraph: 3.1

ModelNet40:
  num_layers: 1
  hid_dim: 256
  proj_dim: 256
  lr: 5.0e-03
  weight_decay: 5.0e-05
  drop_feature_rate: 0.0
  drop_incidence_rate: 0.4
  tau_n: 0.35
  tau_g: 0.35
  tau_m: 0.9
  w_g: 0.25
  w_m: 0.125
  epochs: 200
  batch_size_1: null
  batch_size_2: 8192
  wg: 5
  threshold: 0.2
  c_hypergraph: 2